import { useEffect, useState } from "react";
import "./CityGateway.css";

const LOCALE_KEY = "mcp:citizen:lang:v2";
const strings = {
  en: {
    home:"Home", help:"Get civic help", how:"How it works", city:"Know your city", explorer:"City explorer", languages:"Language", other:"Request another language",
    eyebrow:"YOUR CITY. A LITTLE EASIER TO NAVIGATE.", title:"A hundred public offices.", accent:"One place to start.", intro:"A missed garbage pickup, a damaged road or a confusing government office. You shouldn't need to understand the bureaucracy to find your next step.",
    start:"Get civic help", see:"See how it works", safety:"Independent civic guidance, not a government portal. We do not file a complaint on your behalf.",
    mock:"AN EVERYDAY CITY PROBLEM", example:"What needs attention?", waste:"Garbage or waste", road:"Road damage", drain:"Drainage", location:"Next: tell us where it happened", what:"What brings you here?", choose:"Start with what you're trying to do.", card1:"I need help with a civic problem", card1body:"Describe the issue and its location. Get guidance and official links where available.", card1cta:"Start with the problem",card2:"I want to understand my city",card2body:"Understand elected representatives, municipal officials and public agencies.",card2cta:"Explore city government",card3:"I want to know what happens next",card3body:"Know the difference between preparing a draft and officially submitting a complaint.",card3cta:"Understand follow-up",
    steps:"How it works", stepsTitle:"Three useful steps, without the jargon.", step1:"Tell us what happened",step1body:"Describe a problem in everyday language. You don't need to know the ward or department.",step2:"Tell us where",step2body:"Add an area, landmark or optional DIGIPIN. Responsibility can change across boundaries.",step3:"Understand the next step",step3body:"Review guidance, prepare your message and use the official channel where available.",allSteps:"Read the full guide",
    know:"KNOW YOUR CITY", knowTitle:"Who actually runs your city?", knowIntro:"Some problems need an official complaint. Others need clarity about which institution is responsible.", mayor:"Mayor, councillor or commissioner?", mayorBody:"Different roles have different powers, depending on state and city laws.",whoRoad:"Who maintains this road?",whoRoadBody:"A municipal corporation, development authority or another agency? Ownership matters.",grievance:"Where does a complaint go?",grievanceBody:"Learn what is drafted, what is actually filed, and what can be tracked.", research:"Cities we're learning from", caveat:"City-specific office responsibilities must be verified before being presented as definitive.", lastTitle:"Something in your neighbourhood needs attention?", lastBody:"Begin with the issue. We'll help you work out the next step.", footer:"Independent civic information. Not a government service.",
    guideEyebrow:"HOW MYCITYPULSE WORKS",guideTitle:"You know what's wrong.",guideAccent:"We help with what comes next.",guideIntro:"The right public office may depend on the issue, the exact location and which agency maintains an asset. Here's what MyCityPulse does today.",
    g1:"Describe the problem",g1body:"Start with garbage, roads, drainage or your own words. You do not need to identify the department.",g2:"Add the location",g2body:"Enter a city, locality and landmark; DIGIPIN is optional. We use this context to prepare useful guidance.",g3:"Review the suggested route",g3body:"Check the category, possible responsible service and a message draft. For Ahmedabad, use the linked municipal grievance channel where appropriate. Other cities may not have verified routing yet.",g4:"File officially, then keep the reference",g4body:"Copy the draft and submit it yourself on the authority's official website. Save the official acknowledgement number and filing date if you receive them. A locally saved note is not an official complaint.",
    noteTitle:"Important: a drafted report is not a filed complaint.",noteBody:"MyCityPulse currently helps prepare messages and points to official channels. It cannot promise an official response or a seven-working-day resolution. Any suggested follow-up date is only a reminder calculated from a date you enter.",
    roles:"WHO RUNS THE CITY?", rolesTitle:"Authority and accountability aren't always in one office.", r1:"Mayor and elected council",r1b:"Represent residents, deliberate and exercise powers defined by state municipal law.",r2:"Municipal commissioner",r2b:"Usually leads municipal administration and execution under the applicable law.",r3:"Other public agencies",r3b:"Development authorities, state agencies and utilities may be responsible for particular assets.", rnote:"The exact division of responsibility differs by state, city and type of issue.",
    distinct:"THREE USEFUL DISTINCTIONS",distinctTitle:"A contact number alone isn't the answer.", d1:"Responsible in law",d1b:"Who is legally assigned the function?",d2:"Responsible in practice",d2b:"Who currently manages the road, drain or service?",d3:"Accountable to you",d3b:"Which official channel can accept a grievance and provide a reference?",
    faq:"QUESTIONS YOU MAY HAVE", q1:"Is MyCityPulse a government portal?",a1:"No. It is an independent civic information service and does not speak for a government body.",q2:"Does submitting here file a complaint?",a2:"No. The current experience prepares guidance and a draft. You must use the relevant authority's official process to file. Check for an acknowledgement from that authority.",q3:"Can I expect a reply within seven working days?",a3:"We cannot guarantee that. The seven-working-day option prepares a request and can estimate a reminder after you enter an official filing date; it is not a service promise.",q4:"What happens to my location and details?",a4:"The current civic-help experience uses the information you enter to prepare a draft and can save notes locally on your device. Do not enter sensitive personal information unless needed. Check the specific official portal's privacy terms when filing.",q5:"What if my area has no verified routing?",a5:"Treat suggestions as guidance, not a confirmed assignment. Use the relevant government's official directory or grievance portal.", q6:"Can I read this in another language?",a6:"English is the default. You can choose Gujarati or Marathi on these guide pages and in the civic-help flow, or request another language.",
    exploreLink:"Explore existing city information", introLink:"Back to home", privacy:"Privacy & limitations", source:"For deeper reading: Nāgrika's Governance Series", translated:"Translation choices are provided for accessibility; verify official terminology against the original source."
  },
  gu: {
    home:"મુખ્ય પાનું",help:"નાગરિક મદદ",how:"કેવી રીતે કામ કરે છે",city:"તમારા શહેરને જાણો",explorer:"શહેરોની માહિતી",languages:"ભાષા",other:"બીજી ભાષા માટે વિનંતી",
    eyebrow:"તમારું શહેર. સમજવું થોડું સરળ.",title:"સરકારી કચેરીઓ અનેક.",accent:"શરૂઆત એક જગ્યાએ.",intro:"કચરો ન ઉપડવો, રસ્તો તૂટેલો હોવો કે કઈ કચેરીએ જવું તે સમજ ન પડવી. આગળ શું કરવું તે જાણવા માટે આખી વ્યવસ્થા સમજવી જરૂરી નથી.",
    start:"નાગરિક મદદ મેળવો",see:"કેવી રીતે કામ કરે છે",safety:"આ સ્વતંત્ર નાગરિક માર્ગદર્શન છે, સરકારી પોર્ટલ નથી. અમે તમારા વતી ફરિયાદ દાખલ કરતા નથી.",
    mock:"રોજિંદી શહેરની સમસ્યા",example:"શું સમસ્યા છે?",waste:"કચરો",road:"તૂટેલો રસ્તો",drain:"ગટર / પાણી ભરાવું",location:"આગળ: સ્થળ જણાવો",what:"તમે શા માટે આવ્યા છો?",choose:"તમારી જરૂરિયાતથી શરૂઆત કરો.",card1:"નાગરિક સમસ્યામાં મદદ જોઈએ",card1body:"સમસ્યા અને સ્થળ જણાવો. ઉપલબ્ધ હોય ત્યાં સત્તાવાર લિંક અને માર્ગદર્શન મેળવો.",card1cta:"સમસ્યાથી શરૂઆત કરો",card2:"મારા શહેરને સમજવું છે",card2body:"ચૂંટાયેલા પ્રતિનિધિઓ, અધિકારીઓ અને જાહેર સંસ્થાઓને સમજો.",card2cta:"શહેરનું શાસન જાણો",card3:"આગળ શું થશે તે જાણવું છે",card3body:"ફરિયાદનો ડ્રાફ્ટ તૈયાર કરવો અને સત્તાવાર ફરિયાદ દાખલ કરવી અલગ બાબતો છે.",card3cta:"આગળની પ્રક્રિયા",
    steps:"કેવી રીતે કામ કરે છે",stepsTitle:"સરળ ત્રણ પગલાં.",step1:"શું બન્યું તે કહો",step1body:"સાદી ભાષામાં સમસ્યા જણાવો. વોર્ડ કે વિભાગનું નામ જાણવું જરૂરી નથી.",step2:"સ્થળ જણાવો",step2body:"વિસ્તાર, ઓળખી શકાય એવું સ્થળ કે વૈકલ્પિક DIGIPIN આપો.",step3:"આગળનું પગલું સમજો",step3body:"માર્ગદર્શન વાંચો, ડ્રાફ્ટ બનાવો અને ઉપલબ્ધ સત્તાવાર ચેનલનો ઉપયોગ કરો.",allSteps:"સંપૂર્ણ માર્ગદર્શન",
    know:"તમારા શહેરને જાણો",knowTitle:"તમારું શહેર ખરેખર કોણ ચલાવે છે?",knowIntro:"કેટલીક સમસ્યામાં ફરિયાદ કરવાની હોય છે; બીજીમાં જવાબદાર સંસ્થા સમજવી પડે.",mayor:"મેયર, કોર્પોરેટર કે કમિશનર?",mayorBody:"રાજ્ય અને શહેરના કાયદા મુજબ તેમની સત્તાઓ જુદી હોય છે.",whoRoad:"આ રસ્તાની જવાબદારી કોની?",whoRoadBody:"મહાનગરપાલિકા, વિકાસ સત્તામંડળ કે બીજી એજન્સી?",grievance:"ફરિયાદ ક્યાં જાય છે?",grievanceBody:"ડ્રાફ્ટ, સત્તાવાર નોંધણી અને ટ્રેકિંગ વચ્ચેનો તફાવત.",research:"અમે અભ્યાસ કરતા શહેરો",caveat:"કચેરીની જવાબદારી દર્શાવતા પહેલાં શહેર પ્રમાણે ચકાસણી જરૂરી છે.",lastTitle:"તમારા વિસ્તારમાં કોઈ સમસ્યા છે?",lastBody:"સમસ્યા જણાવો. આગળનું પગલું સમજવામાં મદદ મળશે.",footer:"સ્વતંત્ર નાગરિક માહિતી. સરકારી સેવા નથી.",
    guideEyebrow:"MYCITYPULSE કેવી રીતે કામ કરે છે",guideTitle:"સમસ્યા તમને ખબર છે.",guideAccent:"આગળ શું કરવું તે સમજીએ.",guideIntro:"સાચી કચેરી સમસ્યા, સ્થળ અને સંપત્તિની જવાબદારી પર આધારિત હોઈ શકે છે. હાલની સેવા આ રીતે કામ કરે છે.",
    g1:"સમસ્યા સમજાવો",g1body:"કચરો, રસ્તા, ગટર કે તમારા પોતાના શબ્દોમાં લખો. વિભાગ શોધવાની જરૂર નથી.",g2:"સ્થળ ઉમેરો",g2body:"શહેર, વિસ્તાર અને નજીકનું સ્થળ લખો; DIGIPIN વૈકલ્પિક છે.",g3:"સૂચવેલ રસ્તો તપાસો",g3body:"શ્રેણી, સંભવિત સેવા અને ડ્રાફ્ટ તપાસો. અમદાવાદ માટે ઉપલબ્ધ સત્તાવાર ફરિયાદ ચેનલ વાપરો. બીજા શહેરોનું રૂટિંગ ચકાસાયેલું ન પણ હોય.",g4:"સત્તાવાર ફરિયાદ કરી નંબર સાચવો",g4body:"ડ્રાફ્ટ કૉપી કરી સંબંધિત સરકારી પોર્ટલ પર જાતે દાખલ કરો. સત્તાવાર નોંધણી નંબર અને તારીખ સાચવો. ઉપકરણ પર સાચવેલી નોંધ ફરિયાદ નથી.",
    noteTitle:"મહત્વપૂર્ણ: ડ્રાફ્ટ એટલે નોંધાયેલી ફરિયાદ નહીં.",noteBody:"MyCityPulse હાલ ડ્રાફ્ટ અને સત્તાવાર લિંક આપવામાં મદદ કરે છે. સાત કામકાજના દિવસમાં જવાબની ખાતરી આપતું નથી. તારીખ પરથી ગણેલું રિમાઇન્ડર માત્ર અંદાજ છે.",
    roles:"શહેર કોણ ચલાવે છે?",rolesTitle:"સત્તા અને જવાબદારી હંમેશાં એક જ કચેરીમાં નથી.",r1:"મેયર અને ચૂંટાયેલી સભા",r1b:"નાગરિક પ્રતિનિધિત્વ અને રાજ્ય કાયદા હેઠળની સત્તાઓ.",r2:"મ્યુનિસિપલ કમિશનર",r2b:"કાયદા મુજબ વહીવટ અને અમલીકરણનું નેતૃત્વ.",r3:"અન્ય જાહેર એજન્સીઓ",r3b:"વિકાસ સત્તામંડળ, રાજ્ય એજન્સી અને ઉપયોગિતા સંસ્થાઓ.",rnote:"ચોક્કસ જવાબદારી શહેર, રાજ્ય અને સમસ્યા પ્રમાણે બદલાય છે.",
    distinct:"ત્રણ મહત્વના તફાવત",distinctTitle:"માત્ર ફોન નંબર પૂરતો જવાબ નથી.",d1:"કાયદાકીય જવાબદારી",d1b:"કાયદા મુજબ કામ કોને સોંપાયું છે?",d2:"વાસ્તવિક જવાબદારી",d2b:"હાલ કામગીરી કોણ કરે છે?",d3:"નાગરિક સામે જવાબદારી",d3b:"ફરિયાદ ક્યાં કરી શકો અને નંબર ક્યાંથી મળશે?",
    faq:"વારંવાર પૂછાતા પ્રશ્નો",q1:"શું આ સરકારી પોર્ટલ છે?",a1:"ના. આ સ્વતંત્ર નાગરિક માહિતી સેવા છે.",q2:"અહીં લખવાથી ફરિયાદ દાખલ થાય છે?",a2:"ના. હાલ ડ્રાફ્ટ બને છે. સત્તાવાર નોંધણી માટે સંબંધિત સરકારી ચેનલનો ઉપયોગ કરો.",q3:"સાત કામકાજના દિવસમાં જવાબ મળશે?",a3:"ખાતરી આપી શકાતી નથી. આ ફક્ત વિનંતી અને અંદાજિત રિમાઇન્ડર માટે છે.",q4:"મારી માહિતીનું શું થાય છે?",a4:"ડ્રાફ્ટ માટે આપેલી માહિતી વપરાય છે; નોંધો તમારા ઉપકરણ પર સાચવી શકાય છે. જરૂરી ન હોય તેવી વ્યક્તિગત માહિતી ન આપો.",q5:"મારા વિસ્તારની જવાબદાર કચેરી ચકાસેલી ન હોય તો?",a5:"આ માહિતી માર્ગદર્શન માનો; સત્તાવાર સરકારી ડિરેક્ટરી તપાસો.",q6:"બીજી ભાષામાં વાંચી શકું?",a6:"અંગ્રેજી મૂળ ભાષા છે. ગુજરાતી, મરાઠી પસંદ કરી શકો અથવા નવી ભાષાની વિનંતી કરી શકો.",
    exploreLink:"શહેરોની માહિતી જુઓ",introLink:"મુખ્ય પાને પાછા",privacy:"ગોપનીયતા અને મર્યાદાઓ",source:"વધુ વાંચો: Nāgrika ની Governance Series",translated:"સત્તાવાર શબ્દપ્રયોગ મૂળ સરકારી સ્ત્રોતથી ચકાસવો."
  },
  mr: {
    home:"मुख्यपृष्ठ",help:"नागरी मदत",how:"कसे काम करते",city:"तुमचे शहर जाणून घ्या",explorer:"शहरांची माहिती",languages:"भाषा",other:"दुसऱ्या भाषेची विनंती",
    eyebrow:"तुमचं शहर. समजून घेणं सोपं.",title:"सरकारी कार्यालयं अनेक.",accent:"सुरुवात एकाच ठिकाणी.",intro:"कचरा न उचलणे, रस्ता खराब असणे किंवा कोणत्या कार्यालयात जावे हे न समजणे. पुढचं पाऊल शोधण्यासाठी संपूर्ण प्रशासकीय रचना समजण्याची गरज नाही.",
    start:"नागरी मदत मिळवा",see:"कसे काम करते",safety:"हे स्वतंत्र नागरी मार्गदर्शन आहे, सरकारी पोर्टल नाही. आम्ही तुमच्या वतीने तक्रार दाखल करत नाही.",
    mock:"शहरातील रोजची समस्या",example:"कशाकडे लक्ष द्यायचं?",waste:"कचरा",road:"रस्त्याची दुरवस्था",drain:"निचरा / पाणी साचणे",location:"पुढे: ठिकाण सांगा",what:"तुम्ही कशासाठी आला आहात?",choose:"तुमच्या गरजेपासून सुरुवात करा.",card1:"नागरी समस्येसाठी मदत हवी",card1body:"समस्या आणि ठिकाण लिहा. उपलब्ध असल्यास अधिकृत दुवे आणि मार्गदर्शन मिळवा.",card1cta:"समस्येपासून सुरुवात",card2:"माझं शहर समजून घ्यायचं आहे",card2body:"लोकप्रतिनिधी, अधिकारी आणि सार्वजनिक संस्थांची भूमिका समजून घ्या.",card2cta:"शहर प्रशासन जाणून घ्या",card3:"पुढे काय होईल हे जाणून घ्यायचं आहे",card3body:"तक्रारीचा मसुदा आणि अधिकृत दाखल तक्रार यातला फरक समजून घ्या.",card3cta:"पुढची प्रक्रिया",
    steps:"कसे काम करते",stepsTitle:"तीन सोपी पावलं.",step1:"काय झालं ते सांगा",step1body:"सोप्या शब्दांत समस्या लिहा. प्रभाग किंवा विभाग माहीत असण्याची गरज नाही.",step2:"ठिकाण सांगा",step2body:"परिसर, खूण किंवा ऐच्छिक DIGIPIN द्या. हद्दीनुसार जबाबदारी बदलू शकते.",step3:"पुढचं पाऊल समजून घ्या",step3body:"मार्गदर्शन पाहा, मसुदा तयार करा आणि उपलब्ध अधिकृत माध्यम वापरा.",allSteps:"संपूर्ण मार्गदर्शन",
    know:"तुमचे शहर जाणून घ्या",knowTitle:"तुमचं शहर नेमकं कोण चालवतं?",knowIntro:"काही प्रश्नांसाठी तक्रार गरजेची असते; इतरांसाठी जबाबदार संस्था समजून घेणं महत्त्वाचं.",mayor:"महापौर, नगरसेवक की आयुक्त?",mayorBody:"राज्य आणि शहराच्या कायद्यानुसार प्रत्येकाचे अधिकार वेगळे असतात.",whoRoad:"हा रस्ता कोण सांभाळतो?",whoRoadBody:"महापालिका, विकास प्राधिकरण की दुसरी संस्था?",grievance:"तक्रार कुठे जाते?",grievanceBody:"मसुदा, अधिकृत नोंदणी आणि पाठपुरावा यातला फरक.",research:"आम्ही अभ्यास करत असलेली शहरे",caveat:"शहरनिहाय जबाबदाऱ्या दाखवण्यापूर्वी पडताळणी आवश्यक आहे.",lastTitle:"तुमच्या परिसरात काही समस्या आहे?",lastBody:"समस्येपासून सुरुवात करा. पुढची दिशा शोधू.",footer:"स्वतंत्र नागरी माहिती. सरकारी सेवा नाही.",
    guideEyebrow:"MYCITYPULSE कसे काम करते",guideTitle:"समस्या तुम्हाला ठाऊक आहे.",guideAccent:"पुढचं पाऊल समजून घेऊ.",guideIntro:"योग्य कार्यालय समस्या, अचूक ठिकाण आणि मालमत्तेच्या जबाबदारीनुसार बदलू शकतं. सध्याची सेवा अशी आहे.",
    g1:"समस्या लिहा",g1body:"कचरा, रस्ते, पाणीनिचरा किंवा स्वतःच्या शब्दांत लिहा. विभाग माहीत असण्याची गरज नाही.",g2:"ठिकाण जोडा",g2body:"शहर, परिसर आणि जवळची खूण लिहा; DIGIPIN ऐच्छिक आहे.",g3:"सुचवलेला मार्ग तपासा",g3body:"वर्ग, संभाव्य सेवा आणि मसुदा तपासा. अहमदाबादसाठी उपलब्ध अधिकृत तक्रार दुवा वापरा. इतर शहरांचं मार्गदर्शन अजून पडताळलेलं नसेल.",g4:"अधिकृत तक्रार करून क्रमांक नोंदवा",g4body:"मसुदा कॉपी करून अधिकृत सरकारी संकेतस्थळावर स्वतः दाखल करा. पोचपावती क्रमांक आणि तारीख जतन करा. फोनवर साठवलेली नोंद ही अधिकृत तक्रार नाही.",
    noteTitle:"महत्त्वाचं: मसुदा म्हणजे दाखल तक्रार नाही.",noteBody:"MyCityPulse सध्या मसुदा तयार करतो आणि अधिकृत दुवे देतो. सात कामकाजाच्या दिवसांत उत्तराची हमी नाही. तारखेवरून काढलेली आठवण ही फक्त अंदाज आहे.",
    roles:"शहर कोण चालवतं?",rolesTitle:"अधिकार आणि जबाबदारी कायम एकाच कार्यालयात नसतात.",r1:"महापौर आणि निवडून आलेली परिषद",r1b:"नागरिकांचं प्रतिनिधित्व आणि राज्य कायद्यानुसार अधिकार.",r2:"महापालिका आयुक्त",r2b:"कायद्यानुसार प्रशासन आणि अंमलबजावणीचं नेतृत्व.",r3:"इतर सार्वजनिक संस्था",r3b:"विकास प्राधिकरण, राज्य संस्था आणि सार्वजनिक सुविधा विभाग.",rnote:"नेमकी जबाबदारी राज्य, शहर आणि समस्येनुसार बदलते.",
    distinct:"तीन महत्त्वाचे फरक",distinctTitle:"फक्त फोन नंबर म्हणजे पूर्ण उत्तर नाही.",d1:"कायदेशीर जबाबदारी",d1b:"कायद्याने काम कोणाकडे आहे?",d2:"प्रत्यक्ष जबाबदारी",d2b:"सध्या सेवा किंवा रस्त्याची देखभाल कोण करतं?",d3:"नागरिकांप्रती उत्तरदायित्व",d3b:"तक्रार कुठे दाखल करता येते आणि पावती कुठे मिळते?",
    faq:"सामान्य प्रश्न",q1:"MyCityPulse सरकारी पोर्टल आहे का?",a1:"नाही. ही स्वतंत्र नागरी माहिती सेवा आहे.",q2:"इथे लिहिल्याने तक्रार दाखल होते का?",a2:"नाही. सध्या मसुदा तयार होतो. अधिकृत तक्रारीसाठी सरकारी माध्यम वापरा.",q3:"सात कामकाजाच्या दिवसांत उत्तर मिळेल का?",a3:"याची हमी देता येत नाही. ही सुविधा विनंती आणि अंदाजित आठवणीसाठी आहे.",q4:"माझ्या माहितीचं काय होतं?",a4:"मसुद्यासाठी माहिती वापरली जाते; तुमच्या उपकरणावर नोंद साठवता येते. अनावश्यक वैयक्तिक माहिती टाळा.",q5:"माझ्या भागाची जबाबदार संस्था पडताळलेली नसेल तर?",a5:"सूचना मार्गदर्शन म्हणून घ्या आणि अधिकृत सरकारी निर्देशिका तपासा.",q6:"दुसऱ्या भाषेत वाचता येईल का?",a6:"इंग्रजी मूळ भाषा आहे. मराठी, गुजराती निवडा किंवा दुसऱ्या भाषेची विनंती करा.",
    exploreLink:"शहरांची माहिती",introLink:"मुख्यपृष्ठावर परत",privacy:"गोपनीयता आणि मर्यादा",source:"अधिक वाचा: Nāgrika Governance Series",translated:"अधिकृत संज्ञा मूळ सरकारी स्रोताशी पडताळून घ्या."
  }
};

function useGuideLocale(pageTitle) {
  const [lang, setLang] = useState(() => {
    try { const saved = localStorage.getItem(LOCALE_KEY); return strings[saved] ? saved : "en"; } catch { return "en"; }
  });
  useEffect(() => {
    document.title = pageTitle + " | MyCityPulse";
    document.documentElement.lang = lang;
  }, [lang, pageTitle]);
  const changeLanguage = (next) => {
    setLang(next);
    try { localStorage.setItem(LOCALE_KEY, next); } catch { /* Optional local preference */ }
  };
  return { t: strings[lang], lang, changeLanguage };
}
const needLanguage = "mailto:hello@mycitypulse.in?subject=MyCityPulse%20language%20request";

function Shell({children, t, lang, changeLanguage, current}) {
  return <div className="mcg-root">
    <a className="mcg-skip" href="#main-content">Skip to content</a>
    <header className="mcg-header">
      <div className="mcg-wrap mcg-nav">
        <a className="mcg-brand" href="/" aria-label="MyCityPulse home"><span className="mcg-logo" aria-hidden="true"><i/><i/><i/><i/></span><span>mycity<b>pulse</b><small>.in</small></span></a>
        <nav className="mcg-links" aria-label="Main navigation">
          <a href="/" aria-current={current === "home" ? "page" : undefined}>{t.home}</a>
          <a href="/help">{t.help}</a>
          <a href="/how-it-works" aria-current={current === "how" ? "page" : undefined}>{t.how}</a>
          <a href="/#know">{t.city}</a>
          <a href="/explore">{t.explorer}</a>
        </nav>
        <div className="mcg-language"><label className="mcg-sr" htmlFor="mcg-language">{t.languages}</label><select id="mcg-language" aria-label={t.languages} value={lang} onChange={e=>changeLanguage(e.target.value)}><option value="en">English</option><option value="gu">ગુજરાતી</option><option value="mr">मराठी</option></select></div>
      </div>
    </header>
    <main id="main-content">{children}</main>
    <footer className="mcg-footer"><div className="mcg-wrap mcg-footer-inner"><a href="/" className="mcg-footer-name">MyCityPulse</a><p>{t.footer}</p><div><a href="/how-it-works#privacy">{t.privacy}</a><a href={needLanguage}>{t.other} ↗</a></div></div></footer>
  </div>;
}

function LinkCard({mark,title,body,to,label}) {
  return <article className="mcg-card"><span className="mcg-card-mark" aria-hidden="true">{mark}</span><h3>{title}</h3><p>{body}</p><a href={to}>{label} <span aria-hidden="true">→</span></a></article>;
}

export function HomeLanding() {
  const { t,lang,changeLanguage } = useGuideLocale("Home");
  return <Shell t={t} lang={lang} changeLanguage={changeLanguage} current="home">
    <section className="mcg-hero mcg-wrap">
      <div><p className="mcg-eyebrow">{t.eyebrow}</p><h1>{t.title}<br/><em>{t.accent}</em></h1><p className="mcg-lead">{t.intro}</p><div className="mcg-actions"><a className="mcg-button mcg-primary" href="/help">{t.start} ↗</a><a className="mcg-button mcg-outline" href="/how-it-works">{t.see} →</a></div><p className="mcg-fine">{t.safety}</p></div>
      <div className="mcg-illustration" aria-label={t.example}><div className="mcg-illustration-top"><span>MYCITYPULSE / CIVIC HELP</span><span>01 / 03</span></div><div className="mcg-illustration-body"><p className="mcg-eyebrow">{t.mock}</p><h2>{t.example}</h2><div className="mcg-choice active"><span>♻</span>{t.waste}<b>✓</b></div><div className="mcg-choice"><span>⌁</span>{t.road}</div><div className="mcg-choice"><span>≋</span>{t.drain}</div><div className="mcg-illustration-bottom">{t.location} <span>↗</span></div></div></div>
    </section>
    <section className="mcg-band"><div className="mcg-wrap mcg-section"><p className="mcg-eyebrow">{t.what}</p><h2>{t.choose}</h2><div className="mcg-cards"><LinkCard mark="↗" title={t.card1} body={t.card1body} to="/help" label={t.card1cta}/><LinkCard mark="⌂" title={t.card2} body={t.card2body} to="/#know" label={t.card2cta}/><LinkCard mark="☷" title={t.card3} body={t.card3body} to="/how-it-works#filing" label={t.card3cta}/></div></div></section>
    <section className="mcg-wrap mcg-section mcg-two-col"><div><p className="mcg-eyebrow">{t.steps}</p><h2>{t.stepsTitle}</h2><a className="mcg-button mcg-outline" href="/how-it-works">{t.allSteps} →</a></div><div className="mcg-list">{[[t.step1,t.step1body],[t.step2,t.step2body],[t.step3,t.step3body]].map(([h,p],i)=><div className="mcg-list-item" key={h}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{h}</h3><p>{p}</p></div></div>)}</div></section>
    <section className="mcg-band" id="know"><div className="mcg-wrap mcg-section"><p className="mcg-eyebrow">{t.know}</p><h2>{t.knowTitle}</h2><p className="mcg-section-lead">{t.knowIntro}</p><div className="mcg-cards"><LinkCard mark="♜" title={t.mayor} body={t.mayorBody} to="/how-it-works#governance" label={t.allSteps}/><LinkCard mark="▦" title={t.whoRoad} body={t.whoRoadBody} to="/how-it-works#responsibility" label={t.allSteps}/><LinkCard mark="◉" title={t.grievance} body={t.grievanceBody} to="/how-it-works#filing" label={t.allSteps}/></div><div className="mcg-cities"><strong>{t.research}</strong><div><a href="/ahmedabad">Ahmedabad ↗</a><span>Thane</span><span>Mira-Bhayandar</span><span>Guwahati</span></div><p>{t.caveat}</p><a href="/explore" className="mcg-text-link">{t.exploreLink} →</a></div></div></section>
    <section className="mcg-wrap mcg-section"><div className="mcg-cta"><div><h2>{t.lastTitle}</h2><p>{t.lastBody}</p></div><a className="mcg-button mcg-primary" href="/help">{t.start} ↗</a></div></section>
  </Shell>;
}

export function HowItWorksGuide() {
  const { t, lang, changeLanguage } = useGuideLocale("How it works");
  const steps = [[t.g1,t.g1body],[t.g2,t.g2body],[t.g3,t.g3body],[t.g4,t.g4body]];
  const qs = [[t.q1,t.a1],[t.q2,t.a2],[t.q3,t.a3],[t.q4,t.a4],[t.q5,t.a5],[t.q6,t.a6]];
  return <Shell t={t} lang={lang} changeLanguage={changeLanguage} current="how">
    <section className="mcg-wrap mcg-guide-hero"><p className="mcg-eyebrow">{t.guideEyebrow}</p><h1>{t.guideTitle}<br/><em>{t.guideAccent}</em></h1><p className="mcg-lead">{t.guideIntro}</p></section>
    <section className="mcg-band"><div className="mcg-wrap mcg-section"><div className="mcg-flow">{steps.map(([h,p],i)=><article key={h} id={i===3?"filing":undefined}><span className="mcg-step-number">{String(i+1).padStart(2,"0")}</span><div><h2>{h}</h2><p>{p}</p></div></article>)}</div><div className="mcg-notice" role="note"><strong>{t.noteTitle}</strong><p>{t.noteBody}</p></div><div className="mcg-actions"><a href="/help" className="mcg-button mcg-primary">{t.start} ↗</a><a href="/" className="mcg-button mcg-outline">{t.introLink} →</a></div></div></section>
    <section id="governance" className="mcg-wrap mcg-section mcg-two-col"><div><p className="mcg-eyebrow">{t.roles}</p><h2>{t.rolesTitle}</h2><p className="mcg-fine">{t.rnote}</p></div><div className="mcg-list">{[[t.r1,t.r1b],[t.r2,t.r2b],[t.r3,t.r3b]].map(([h,p],i)=><div className="mcg-list-item" key={h}><span>{["⌂","⚙","⌗"][i]}</span><div><h3>{h}</h3><p>{p}</p></div></div>)}</div></section>
    <section id="responsibility" className="mcg-band"><div className="mcg-wrap mcg-section"><p className="mcg-eyebrow">{t.distinct}</p><h2>{t.distinctTitle}</h2><div className="mcg-cards">{[[t.d1,t.d1b],[t.d2,t.d2b],[t.d3,t.d3b]].map(([h,p],i)=><article className="mcg-card" key={h}><span className="mcg-card-mark">{String(i+1).padStart(2,"0")}</span><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
    <section className="mcg-wrap mcg-section" id="privacy"><p className="mcg-eyebrow">{t.faq}</p><h2>{t.privacy}</h2><div className="mcg-faq">{qs.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}</summary><p>{a}</p></details>)}</div><p className="mcg-fine">{t.translated}</p><a href="https://www.nagrika.org/post/governanceseries" target="_blank" rel="noopener noreferrer" className="mcg-text-link">{t.source} ↗</a><div className="mcg-actions"><a href="/help" className="mcg-button mcg-primary">{t.start} ↗</a><a href="/" className="mcg-button mcg-outline">{t.introLink} →</a></div></section>
  </Shell>;
}
